# Generated by Django 3.2.1 on 2023-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0002_alter_stuff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
