# Generated by Django 3.2.1 on 2023-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0003_alter_stuff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
