# Generated by Django 3.2.1 on 2023-12-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoIt', '0004_alter_stuff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
